services:
  paratest:
    image: parasoft/paratest:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./thoughtfusion:/thoughtfusion:ro  # for development
    init: true
